CREATE DATABASE ApiCliente

CREATE TABLE CLIENTE (
ID INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(30),
CPF VARCHAR(11),
EMAIL VARCHAR(100),
DATANASCIMENTO DATETIME NOT NULL
);

CREATE TABLE ENDERECO (
ID INT PRIMARY KEY IDENTITY(1,1),
CLIENTEID INT NOT NULL,
LOGRADOURO VARCHAR(50) NOT NULL,
BAIRRO VARCHAR(40),
CIDADE VARCHAR(40),
ESTADO VARCHAR(40)
  CONSTRAINT FK_CLIEND FOREIGN KEY (CLIENTEID) REFERENCES CLIENTE (ID)
);
